# Default training configuration for DefaultYolov8SegPruner
# Mirrors the basic arguments found in ultralytics/cfg/default.yaml
# Adjust paths and parameters as needed.

# Task type
task: segment
# Model architecture or pretrained weights
model: yolov8n-seg.pt
# Dataset configuration
data: coco128-seg.yaml
# Number of epochs for the initial training run
epochs: 50
# Training batch size
batch: 4
# Input image size
imgsz: 640
